### ISSUE TITLE
1.13.2 Gamemode management not working

### ISSUE THREAD

**Issue by RadialNiner** [EbonJaeger/perworldinventory-kt#117]
I run a spigot server for 1.13.2 with EssentialsX, EssentialsX Chat, EssentialsX Spawn, EssentialsX Protect, Holographic Displays, Multiverse, PermissionsEX, Per world Inventories, ProtocolLib, Shop, Vault and World Border. I installed PWI because I needed to managed inventories and change gamemodes between creative worlds and survival worlds. I am the Owner and in PermisisonsEX I have all the permissions. PWI works great for me, gamemodes change (after disabling the bypass) and inventories change but when my members join there inventories change but gamemodes won't. I am running PWI V2.2.2.

My PWI Config is bellow...
```yaml
##########################################
#  PerWorldInventory configuration file  #
##########################################

# If true, the server will change player's gamemodes when entering a world
# The gamemode set is configured in the worlds.yml file
manage-gamemodes: true

# If true, players will have different inventories for each gamemode
separate-gamemode-inventories: false

# If true, any worlds that are not in the worlds.yml configuration file will share the same inventory
share-if-unconfigured: false

# True if PWI should set the respawn world when a player dies
manage-death-respawn: true

# Disables the nagging message when a world is created on the fly
# Intended for users who know what their doing, and don't need to have worlds configured
disable-nag-message: false

metrics:
  # Choose whether or not to enable metrics sending.
  # See https://bstats.org/getting-started for details.
  enable: true
  # Send the number of configured groups.
  # No group names will be sent!
  send-number-of-groups: true
  # Send the total number of worlds on the server.
  send-number-of-worlds: true

# All settings for players are here:
player:
  # Save and Load players' economy balances. Requires Vault!
  economy: false
  # Load players' ender chests
  ender-chest: true
  # Load players' inventory
  inventory: true
  # All options for player stats are here:
  stats:
    # Load if a player is able to fly
    can-fly: true
    # Load the player's display name
    display-name: false
    # Load a player's exhaustion level
    exhaustion: true
    # Load how much exp a player has
    exp: true
    # Load a player's hunger level
    food: true
    # Load if a player is flying
    flying: true
    # Load how much health a player has
    health: true
    # Load what level the player is
    level: true
    # Load all the potion effects of the player
    potion-effects: true
    # Load the saturation level of the player
    saturation: true
    # Load a player's fall distance
    fall-distance: true
    # Load the fire ticks a player has
    fire-ticks: true
    # Load the maximum amount of air a player can have
    max-air: true
    # Load the current remaining air a player has
    remaining-air: true

# Attempt to figure out which world a player last logged off in
# and save/load the correct data if that world is different.
# REQUIRES MC 1.9.2 OR NEWER
load-data-on-join: false

# Set the level of debug messages shown by PWI.
# INFO: Print general messages
# FINE: Print more detailed messages about what the plugin is doing
# DEBUG: Print detailed messages about everything
logging-level: 'INFO'

# Disables bypass regardless of permission
# Defaults to false
disable-bypass: false

# Set the duration in minutes for player profile information to be cached
cache-duration: 10

# Set the maximum number of player profiles that can be cached at any given time
cache-maximum-limit: 1000
```

And my PWI Worlds file is also bellow...

```yaml
# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - survival
    - survival_nether
    - survival_the_end
    default-gamemode: SURVIVAL
    respawnWorld: survival
  creative:
    worlds:
    - creative_world
    default-gamemode: CREATIVE
    respawnWorld: creative_world
```

I have also attached my permissions file...
```yaml
groups:
  member:
    options:
      default: true
      prefix: '&9&l[Member]&f-&5'
    permissions:
    - modifyworld.*
    - essentials.firework
    - essentials.msg
    - essentials.msg.color
    - essentials.msg.format
    - essentials.suicide
    - essentials.spawn
    - essentials.back.ondeath
    - essentials.home
    - essentials.home.bed
    - essentials.sethome.multiple
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.chat.color
    - essentials.warps.*
    - multiverse.access.*
    - essentials.warp
    - essentials.gamemode
  moderator:
    options:
      default: false
      prefix: '&2&l[Moderator]&f-&5'
    permissions:
    - modifyworld.*
    - essentials.firework
    - essentials.fly
    - essentials.gamemode
    - essentials.msg
    - essentials.msg.color
    - essentials.msg.format
    - essentials.suicide
    - essentials.ban
    - essentials.clearinventory
    - essentials.kill
    - essentials.unban
    - essentials.spawn
    - essentials.setspawn
    - essentials.back
    - essentials.back.ondeath
    - essentials.home
    - essentials.home.bed
    - essentials.sethome.multiple
    - essentials.tpa
    - essentials.tp
    - essentials.tp.others
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.chat.color
    - essentials.joinfullserver
    - multiverse.access.*
    - multiverse.*
    - essentials.warps.*
    - essentials.warp
  owner:
    options:
      default: false
      prefix: '&6&l[Owner]&f-&5'
    permissions:
    - modifyworld.*
    - -essentials.sethome.multiple.unlimited
    - essentials.sethome.multiple
    - '*'
schema-version: 1
```

I would really appreciate some help!
