### ISSUE TITLE
Inventory not persisting in nether.

### ISSUE THREAD

**Issue by Mundayne** [EbonJaeger/perworldinventory-kt#127]
**Describe the bug**
Inventory is not being carried over to a world in the same group.

**To Reproduce**
1. Install Multiverse Core, Multiverse Nether Portals.
2. Create a second set of worlds (normal, nether and end dimensions, in my case `Subs`, `Subs_nether` and `Subs_the_end`.
3. Link `Subs` and `Subs_nether` using MV:NP via the command `/mvnp link nether Subs Subs_nether`.
4. Create group for second world: `/pwi group create sub survival Subs Subs_nether Subs_the_end`.
5. Construct and travel via nether portal in Subs to Subs_nether.
6. Inventory resets (BUG).

**Expected behavior**
Inventory should remain the same.

**Plugin version**
- [x] Using the latest released version of the plugin
- [ ] Using the `legacy` jar

**Server version**
git-Spigot-e5e5c7c-c24abab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Additional context and logs**
```yml
# # world.yml
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
    respawnWorld: world
  sub:
    worlds:
    - Subs
    - Subs_the_end
    - Subs_nether
    default-gamemode: SURVIVAL
    respawnWorld: Subs
```
`config.yml` is default.
