### ISSUE TITLE
Inventory loss with version v2.3.2

### ISSUE THREAD

**Issue by TheoRetisch1** [EbonJaeger/perworldinventory-kt#141]
I was foolish enough to update a productive system today without extensive testing after PerWorldInventory worked reliably for years. I regretted it and had to use player file backups.

I provide the gamemodes 0 and 1 with their own inventories and individually assigned worlds. 

If a player is set to gm1 after a world change, everything runs fine (correct inventory). However, if he switches back to a world where he is set to gamemode 0, his gamemode 0 inventory including his enderchest is deleted. There is no error in the log.

The problem is clearly reproducible and can be traced back to the update from v2.2.2 to v2.3.0. A downgrade fixed the problem.

`separate-gamemode-inventories: true`
```
groups:
  default:
    worlds:
    - weltn
    - End
    - Nether
    - Abbau
    - Event
    - spielwiese
    - Halloween
    default-gamemode: SURVIVAL
  creative:
    worlds:
    - Creative
    default-gamemode: CREATIVE
```

Paper 1.13.2 – 626
PerWorldInventory – 2.3.0
